### PR TITLE
Add support for Linux

### PR DESCRIPTION
**Pull request by Shakarang**
Hello!

We've added support for Linux in the package to allow anyone to use it on CI. There were two issues to fix:
- `URLSession` APIs are not part of Foundation
- `CommonCrypto` does not exist on Linux

### URLSession

`URLSession` is part of `FoundationNetworking` framework on Linux. We've added the import when the framework exists.

### CommonCrypto

As `CommonCrypto` is not available on Linux, we had to use another way to sign the JWT token. We're using Apple made [swift-crypto](https://github.com/apple/swift-crypto). It removes a lot of manual operations as the signature is available in their framework. 

This framework requires macOS 11, so adding it would drop support for macOS 10.15. However, as the latest Xcode only supports macOS 12, this can be acceptable.

### API Changes

We've updated the `APIConfiguration` initialiser to make it throwable when the given key is not valid. This allows to build the private key only once, and throw an error as soon as possible when we know the key is not correct.

### CODE REVIEW

**Review by AvdLee — APPROVED** [review]
Thanks for the detailed PR description, that makes reviewing this high quality PR much easier! I love that we can remove the responsibility of JWT handling to Apple's framework.

Since this is a breaking change, I'll release this under a major version bump. 👌

**Comment by Shakarang** [comment]
Thanks a lot for the quick review 🚀

**Comment by AvdLee** [comment]
@Shakarang could you have a look at the tests? 🙏

**Comment by Shakarang** [comment]
All good now, thanks @AvdLee 🥳

**Pull request merged**
