### PR TITLE
Regenerated code for App Store Connect API 2.2 changes

### PR DESCRIPTION
**Pull request by Workshed**
The latest version of the OpenAPI schema is named 2.2 so the filenames have been updated in the project to match. 
Tweaked the README to add instructions for the jq dependency. 

What led me down the path of updating the schema is that the error from /v1/inAppPurchaseSubmissions can't be decoded in `RequestExecutor`. The line `self.errorResponse = try? APIProvider.jsonDecoder.decode(ErrorResponse.self, from: data)` always results in `nil`. This was due to a `detail` field not being present in the `ErrorResponse` generated object. Unfortunately even the latest schema claims this field will always be present (it's really not), so for this PR I've manually removed it from the required elements in `app_store_connect_api_2.2_openapi.json`. Obviously this manual wrangling of the schema is not ideal but I imagine we'd rather have the error messages returned than not.

### CODE REVIEW

**Comment by MortenGregersen** [comment]
Also, there are sometimes more information for the error in the property `meta` on the ErrorResponse schema: https://github.com/MortenGregersen/Bagbutik/blob/main/Sources/BagbutikSpecDecoder/Spec.swift#L188-L203

**Comment by Workshed** [comment]
> Also, there are sometimes more information for the error in the property `meta` on the ErrorResponse schema: https://github.com/MortenGregersen/Bagbutik/blob/main/Sources/BagbutikSpecDecoder/Spec.swift#L188-L203

There may well be, I've not found an `ErrorResponse` that includes a `meta` property for me to test with however.

**Review by AvdLee — APPROVED** [review]
Thanks a lot, this is a very welcome change!

**Comment by AvdLee** [comment]
@Workshed could you have a look at the tests? 🙏

**Comment by Workshed** [comment]
@AvdLee I've added a fix for the failing test. Is Bitrise triggered manually by yourself?

**Comment by AvdLee** [comment]
Bitrise requires manual approval: 
CleanShot 2023-03-10 at 14 22 58@2x

Quite annoying! But, it's running now! 🙏

**Comment by Workshed** [comment]
Hilariously API 2.3 was released last night

**Pull request merged**
