### PR TITLE
Conforming Response to Codable

### PR DESCRIPTION
**Pull request by marcelmendesfilho**
This very small PR conforms Response object to Codable so it can be used as a generic object.

### CODE REVIEW

**Comment by AvdLee** [comment]
@marcelmendesfilho, thanks for your contribution! Can you elaborate on why you need this change? Btw, the tests are currently failing.

**Comment by marcelmendesfilho** [comment]
hi @AvdLee thanks for asking! The use case is this: I want to create a generic fetcher that accepts any AppStoreConnect request. As an example, see the method signature below:

`func fetcher<Response: Codable>(request: Request<Response>, maxRetries: Int? = 3) async throws -> Response`

Conforming Response to Coddle allows me to have this generic fetcher and I've thought that it would be a nice addition to the package.

**Comment by marcelmendesfilho** [comment]
I'm working on it.

**Comment by marcelmendesfilho** [comment]
@AvdLee looks like we're ready to go with this PR ;-)

**Comment by AvdLee** [comment]
Yes, thanks for fixing the test and your contribution!

**Review by AvdLee — APPROVED** [review]

**Pull request merged**
