### PR TITLE
Add PROCESSING status for Device

### LINKED ISSUE #214: Add new device UDID failed
```json
Error: Failed to decode response:
{
  "data" : {
    "type" : "devices",
    "id" : "83U6TJTZ87",
    "attributes" : {
      "addedDate" : "2022-12-02T09:10:27.669+00:00",
      "name" : "6-2022-0102-0101",
      "deviceClass" : "IPHONE",
      "model" : null,
      "udid" : "00008020-XXXX",
      "platform" : "IOS",
      "status" : "PROCESSING" //< ❌ here error, can not decode `PROCESSING`
    },
    "links" : {
      "self" : "https://api.appstoreconnect.apple.com/v1/devices/XXXX"
    }
  },
  "links" : {
    "self" : "https://api.appstoreconnect.apple.com/v1/devices"
  }
}
```

error message:

Error: dataCorrupted(Swift.DecodingError.Context(codingPath: [StringCodingKey(stringValue: "data", intValue: nil), StringCodingKey(stringValue: "attributes", intValue: nil), StringCodingKey(stringValue: "status", intValue: nil)], debugDescription: "Cannot initialize Status from invalid String value PROCESSING", underlyingError: nil)).

### PR DESCRIPTION
**Pull request by iWECon**
fix #214

### CODE REVIEW

**Review by AvdLee — CHANGES_REQUESTED** [review]
Thanks for your contribution @iWECon. We're generating code automatically, so manual code changes shouldn't be needed. If this state is missing, there must be an updated schema available. 

Could you instead follow [this guide](https://github.com/AvdLee/appstoreconnect-swift-sdk#update-openapi-generated-code) to update the code? 🙏

**Comment by iWECon** [comment]
@AvdLee OK~, I turned off, I will submit it later

**Comment by iWECon** [comment]
@AvdLee I tried, openapi.json it does not seem to add `PROCESSING` status. 

Really bad :(

CleanShot 2022-12-02 at 19 00 48@2x

**Comment by AvdLee** [comment]
@liamnichols would CreateAPI be able to shine here by manually adding that extra enum case? 🤔

**Comment by MortenGregersen** [comment]
Apple should be made aware of the missing case in the OpenAPI spec and documentation. @iWECon have you filed a feedback at Apple we can duplicate?

**Comment by iWECon** [comment]
@MortenGregersen Sorry, I didn't submit feedback to Apple. I'm not familiar with giving feedback to Apple.

**Pull request closed without merging**
