### PR TITLE
Updates to OpenAPI spec version 3.3

### PR DESCRIPTION
**Pull request by mathiasemil**
Updates from OpenAPI spec version 3.0.1 to ~3.2~ 3.3.

### CODE REVIEW

**Comment by mathiasemil** [comment]
I suspect this might break the manual fixes that were made recently in https://github.com/AvdLee/appstoreconnect-swift-sdk/pull/255 and https://github.com/AvdLee/appstoreconnect-swift-sdk/pull/256.

**Comment by AvdLee** [comment]
> I suspect this might break the manual fixes that were made recently in https://github.com/AvdLee/appstoreconnect-swift-sdk/pull/255 and https://github.com/AvdLee/appstoreconnect-swift-sdk/pull/256.

Yes, I'm afraid of that too. Would you be able to merge those into this PR?

**Comment by mathiasemil** [comment]
> > I suspect this might break the manual fixes that were made recently in #255 and #256.
> 
> Yes, I'm afraid of that too. Would you be able to merge those into this PR?

Thanks for reminding me 🙏🏼 
I have updated to spec version 3.3 and re-applied the manual fixes from #255 and #256.

**Review by AvdLee — APPROVED** [review]
Thanks for going over the changes!

**Pull request merged**
