### PR TITLE
Update RateLimit parsing for Multiple values

### PR DESCRIPTION
**Pull request by instanceof**
* Multiple X-Rate-Limit headers can be combined with commas when using HttpURLResponse.value(forHTTPHeaderField:)
* The comma and extra spaces show up in the RateLimit.entries keys.

```
x-rate-limit: user-hour-lim:3600;user-hour-rem:3598;
x-rate-limit: user-minute-lim:150;user-minute-rem:149;
```

becomes:

```
user-hour-lim:3600;user-hour-rem:3598;, user-minute-lim:150;user-minute-rem:149;
                                      ^^
```

```swift
print("Rate Limit: \(rateLimit.entries)")
```

Which was parsed as:

```
Rate Limit: ["user-hour-rem": 3598, ", user-minute-lim": 150, "user-hour-lim": 3600, "user-minute-rem": 149]
or
Rate Limit: [", user-minute-lim": 150, "user-hour-lim": 3600, "user-hour-rem": 3598, "user-minute-rem": 149]
```

* Adds a test for the observed comma space separated headers observed.

See #227

### CODE REVIEW

**Review by AvdLee — APPROVED** [review]
Interesting, thanks for your contribution!

**Comment by instanceof** [comment]
Looks like the comma is added in Foundation here:

https://github.com/apple/swift-corelibs-foundation/blob/7fc59bfa50e8679675d19728245d3e9784c34d5f/Sources/FoundationNetworking/URLSession/HTTP/HTTPMessage.swift#L78

**Comment by instanceof** [comment]
Any other changes requested to merge this PR?

**Comment by AvdLee** [comment]
> Any other changes requested to merge this PR?

Nope, all good! Thanks again!

**Pull request merged**
