### PR TITLE
Added tvOS as Target

### PR DESCRIPTION
**Pull request by karm435**
Added tvOS as Target in package.swift

Related to issue: https://github.com/AvdLee/appstoreconnect-swift-sdk/issues/216

### CODE REVIEW

**Review by AvdLee — APPROVED** [review]

**Comment by AvdLee** [comment]
@karm435 do the tests succeed locally? CI is currently broken, so I need some time to fix that

**Comment by karm435** [comment]
😞 looks like it did not run tests locally. I will run them and see if I
could fix them.

**Comment by karm435** [comment]
I ran the tests locally and looks like that are fine. 
image

**Comment by AvdLee** [comment]
@karm435 they completed, but did the succeed as well?

**Comment by karm435** [comment]
> @karm435 they completed, but did the succeed as well?

They are completed with Green color

image

**Comment by AvdLee** [comment]
Thanks for your contribution @karm435

**Comment by karm435** [comment]
> 

You are welcome. I will see what else I can contribute to as I develop my app.

**Pull request merged**
